### ISSUE TITLE
Doesn't work with Pixel 3

### ISSUE THREAD

**Issue by Mythris29** [amirzaidi/AIDLBridge#2]
Hear me out :) I know you've already warned this won't work with the Pixel devices but on the Pixel 3 this is one of my only hopes to have the pixel launcher without forcing me to use gestures. I disabled the pixel launcher using this method https://www.xda-developers.com/disable-android-pie-gestures-google-pixel-3/ and so far Rootless Launcher is working great except I miss the Google Now cards that the bridge should let me use. 

I get the app not installed error when I try to install the bridge. Is there any possible way you could save us from Google and have a version of the bridge that would work on Pixel devices?

If I'm just an idiot and there is another way to do this...I would also like to know that :)

**Comment by Carbon-Zero** [comment]
Use the launcher that came with the phone. What you are trying to do is idiotic.

**Comment by Mythris29** [comment]
@Carbon-Zero Nice, really classy and professional of you. It's interesting that you went out of your way to not only be unhelpful but also insulting. Do you have a method without root to disable the pixel 3 gestures but keep the pixel 3 launcher? That would have been an intelligent response even if the response was "I don't think it's possible". Please learn to communicate and be a contrbutor to society not just another problem.

**Comment by amirzaidi** [comment]
I'm going to look into giving an option for Pixel users in the future

**Comment by amirzaidi** [comment]
@BlackBearImmortal if you could provide instructions for the "app freezing" that would be appreciated. I've tried adb hide and pm uninstall before but it wouldn't let the user re-use the package name.

**Comment by uninc** [comment]
Lawnfeed apk from a mirror site works on pixel devices . It is essentially the same thing. Looks like AZ works on that project too.

**Comment by amirzaidi** [comment]
You can use aidlbridge.apk on Pixel devices with Shade Launcher
